"""
sample_files.py
===============

Builds a handful of real, openable files for trying the file library, the
G-code viewer, the 3D viewer, the pre-flight check and the 3MF converter
without owning a printer or a slicer.

Nothing here pretends to be something it isn't:
  - the G-code files are generated here, move by move, with honest
    header comments saying so (they are simple test shapes, not tuned
    slicer output);
  - the "Bambu-style" and "Elegoo-style" projects are built by this file in
    the same project layout those slicers write, and say so in their own
    Application metadata - they are not downloads from MakerWorld or
    NexPrint.

The files are only added when the user presses "Add sample files".
"""

import base64
import io
import json
import math
import zipfile

import mesh_tools

CENTER = 135.0
LAYER = 0.2
WIDTH = 0.45
E_PER_MM = (WIDTH * LAYER) / (math.pi * (1.75 / 2) ** 2)


def _square_thumbnail(color, size=48):
    """A flat top-view thumbnail: a coloured square on transparent."""
    r, g, b = color
    px = bytearray()
    for y in range(size):
        for x in range(size):
            inside = 8 <= x < size - 8 and 8 <= y < size - 8
            edge = inside and (x in (8, size - 9) or y in (8, size - 9))
            if inside:
                shade = 0.75 if edge else 1.0
                px += bytes((int(r * shade), int(g * shade), int(b * shade), 255))
            else:
                px += b"\x00\x00\x00\x00"
    return mesh_tools.encode_png(size, size, bytes(px))


class _Writer:
    """Accumulates moves and keeps count of time and filament as it goes."""

    def __init__(self):
        self.lines = []
        self.x, self.y, self.z = CENTER, CENTER, 0.0
        self.seconds = 0.0
        self.e_total = {}
        self.tool = 0

    def cmd(self, text):
        self.lines.append(text)

    def travel(self, x, y, z=None, feed=9000):
        dz = 0 if z is None else z - self.z
        dist = math.sqrt((x - self.x) ** 2 + (y - self.y) ** 2 + dz ** 2)
        self.seconds += dist / (feed / 60)
        zpart = "" if z is None else f" Z{z:.2f}"
        self.cmd(f"G0 X{x:.2f} Y{y:.2f}{zpart} F{feed}")
        self.x, self.y = x, y
        if z is not None:
            self.z = z

    def extrude(self, x, y, feed=3000):
        dist = math.hypot(x - self.x, y - self.y)
        e = dist * E_PER_MM
        self.seconds += dist / (feed / 60)
        self.e_total[self.tool] = self.e_total.get(self.tool, 0.0) + e
        self.cmd(f"G1 X{x:.2f} Y{y:.2f} E{e:.5f} F{feed}")
        self.x, self.y = x, y

    def rect(self, cx, cy, w, d):
        x0, y0, x1, y1 = cx - w / 2, cy - d / 2, cx + w / 2, cy + d / 2
        self.travel(x0, y0)
        for x, y in ((x1, y0), (x1, y1), (x0, y1), (x0, y0)):
            self.extrude(x, y)

    def infill(self, cx, cy, w, d, layer_index, spacing=4.0):
        x0, y0, x1, y1 = cx - w / 2, cy - d / 2, cx + w / 2, cy + d / 2
        if layer_index % 2:
            y = y0 + spacing / 2
            while y < y1:
                self.travel(x0, y)
                self.extrude(x1, y)
                y += spacing
        else:
            x = x0 + spacing / 2
            while x < x1:
                self.travel(x, y0)
                self.extrude(x, y1)
                x += spacing


def _gcode(title, colours, types, body, thumb_color):
    """Wrap moves with a PRINT_START/PRINT_END and Orca-style header comments."""
    w = _Writer()
    body(w)
    grams = sum(v * math.pi * (1.75 / 2) ** 2 * 1.24 / 1000 for v in w.e_total.values())
    secs = int(w.seconds)
    thumb = base64.b64encode(_square_thumbnail(thumb_color)).decode("ascii")
    head = [
        f"; {title}",
        "; generated by Deja Vu1's sample_files.py - a simple test shape, not tuned slicer output",
        "; HEADER_BLOCK_START",
        f"; estimated printing time (normal mode) = {secs // 3600}h {secs % 3600 // 60}m {secs % 60}s",
        f"; total filament used [g] = {grams:.2f}",
        f"; total layer number: {w.layers}",
        "; HEADER_BLOCK_END",
        "; THUMBNAIL_BLOCK_START",
        f"; thumbnail begin 48x48 {len(thumb)}",
    ]
    head += ["; " + thumb[i:i + 78] for i in range(0, len(thumb), 78)]
    head += ["; thumbnail end", "; THUMBNAIL_BLOCK_END",
             "PRINT_START TOOL_TEMP=220 BED_TEMP=60 TOOL=0", "M83", "G90"]
    tail = ["PRINT_END",
            "; CONFIG_BLOCK_START",
            "; printer_model = Snapmaker U1",
            "; nozzle_diameter = 0.4,0.4,0.4,0.4",
            f"; layer_height = {LAYER}",
            f"; filament_type = {';'.join(types)}",
            f"; filament_colour = {';'.join(colours)}",
            "; sparse_infill_density = 20%",
            "; wall_loops = 2",
            "; nozzle_temperature = 220,220,220,220",
            "; hot_plate_temp = 60",
            "; CONFIG_BLOCK_END"]
    return "\n".join(head + w.lines + tail) + "\n"


def calibration_cube():
    def body(w):
        layers = 50
        w.layers = layers
        for i in range(layers):
            w.travel(CENTER - 10, CENTER - 10, round(LAYER * (i + 1), 2))
            w.rect(CENTER, CENTER, 20, 20)
            w.rect(CENTER, CENTER, 20 - 2 * WIDTH, 20 - 2 * WIDTH)
            w.infill(CENTER, CENTER, 18, 18, i)
    return _gcode("20 mm calibration cube", ["#F26A1B"], ["PLA"], body, (242, 106, 27))


def two_colour_coaster():
    def body(w):
        layers = 15
        w.layers = layers
        for i in range(layers):
            if i == 10:
                w.cmd("T1")
                w.tool = 1
            w.travel(CENTER - 30, CENTER - 30, round(LAYER * (i + 1), 2))
            w.rect(CENTER, CENTER, 60, 60)
            w.infill(CENTER, CENTER, 58, 58, i, spacing=1.2 if i in (0, 9, 14) else 4.0)
    return _gcode("Two-colour coaster (T0 base, T1 top)", ["#F26A1B", "#1C1C1E"],
                  ["PLA", "PLA"], body, (40, 40, 44))


def unsafe_example():
    """A cube plus a purge line that runs past the U1's 270 mm bed edge."""
    def body(w):
        layers = 20
        w.layers = layers
        w.travel(250, 20, 0.3)
        w.extrude(290, 20)          # 20 mm beyond the bed - pre-flight must catch it
        for i in range(layers):
            w.travel(CENTER - 10, CENTER - 10, round(LAYER * (i + 1), 2))
            w.rect(CENTER, CENTER, 20, 20)
    return _gcode("Unsafe example: purge line past the bed edge", ["#C8102E"], ["PLA"],
                  body, (200, 16, 46))


def dock_bracket_triangles():
    """An L-shaped bracket: the L profile extruded 40 mm, as closed triangles."""
    profile = [(0, 0), (30, 0), (30, 5), (5, 5), (5, 25), (0, 25)]
    depth = 40.0
    tris = []
    n = len(profile)
    # Caps: fan from the inner corner (5,5), which sees every edge of the L.
    hub = 3
    for k in range(n):
        a, b = profile[k], profile[(k + 1) % n]
        if hub in (k, (k + 1) % n):
            continue
        h = profile[hub]
        tris.append(((h[0], 0, h[1]), (b[0], 0, b[1]), (a[0], 0, a[1])))
        tris.append(((h[0], depth, h[1]), (a[0], depth, a[1]), (b[0], depth, b[1])))
    for k in range(n):
        a, b = profile[k], profile[(k + 1) % n]
        p1, p2 = (a[0], 0, a[1]), (b[0], 0, b[1])
        p3, p4 = (b[0], depth, b[1]), (a[0], depth, a[1])
        tris.append((p1, p2, p3))
        tris.append((p1, p3, p4))
    return tris


def dock_bracket_stl():
    return mesh_tools.to_binary_stl(dock_bracket_triangles(), "Deja Vu1 sample dock bracket")


def _model_xml(triangles, application):
    verts, index, faces = [], {}, []
    for t in triangles:
        ids = []
        for p in t:
            key = tuple(round(c, 4) for c in p)
            if key not in index:
                index[key] = len(verts)
                verts.append(key)
            ids.append(index[key])
        faces.append(ids)
    v = "".join(f'<vertex x="{x}" y="{y}" z="{z}"/>' for x, y, z in verts)
    f = "".join(f'<triangle v1="{a}" v2="{b}" v3="{c}"/>' for a, b, c in faces)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<model unit="millimeter" xml:lang="en-US" '
            'xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">\n'
            f' <metadata name="Application">{application}</metadata>\n'
            f' <resources><object id="1" type="model"><mesh><vertices>{v}</vertices>'
            f'<triangles>{f}</triangles></mesh></object></resources>\n'
            ' <build><item objectid="1" transform="1 0 0 0 1 0 0 0 1 115 115 0"/></build>\n'
            '</model>\n')


def _project_3mf(application, config):
    out = io.BytesIO()
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml",
                   '<?xml version="1.0" encoding="UTF-8"?>\n<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
                   '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
                   '<Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>'
                   '<Default Extension="png" ContentType="image/png"/></Types>')
        z.writestr("_rels/.rels",
                   '<?xml version="1.0" encoding="UTF-8"?>\n<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
                   '<Relationship Target="/3D/3dmodel.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>')
        z.writestr("3D/3dmodel.model", _model_xml(dock_bracket_triangles(), application))
        z.writestr("Metadata/project_settings.config", json.dumps(config, indent=4))
        z.writestr("Metadata/plate_1.png",
                   mesh_tools.png_thumbnail(dock_bracket_triangles(), 128) or b"")
        z.writestr("Metadata/plate_1.gcode", "; sliced for the original printer\nG28\n")
    return out.getvalue()


def bambu_style_project():
    """A project in Bambu Studio's layout, targeting a Bambu printer."""
    return _project_3mf("Deja Vu1 sample in Bambu Studio project layout", {
        "printer_model": "Bambu Lab X1 Carbon",
        "printer_settings_id": "Bambu Lab X1 Carbon 0.4 nozzle",
        "print_settings_id": "0.20mm Standard @BBL X1C",
        "filament_settings_id": ["Bambu PLA Basic @BBL X1C", "Bambu PLA Basic @BBL X1C"],
        "inherits_group": ["0.20mm Standard @BBL X1C", "Bambu PLA Basic @BBL X1C",
                           "Bambu PLA Basic @BBL X1C", "Bambu Lab X1 Carbon 0.4 nozzle"],
        "different_settings_to_system": ["sparse_infill_density;wall_loops", "", "", ""],
        "filament_colour": ["#F26A1B", "#1C1C1E"],
        "filament_type": ["PLA", "PLA"],
        "layer_height": "0.2",
        "sparse_infill_density": "25%",
        "wall_loops": "3",
        "nozzle_diameter": ["0.4"],
        "printable_area": ["0x0", "256x0", "256x256", "0x256"],
        "printable_height": "250",
        "machine_start_gcode": ";===== Bambu X1 start sequence (sample placeholder) =====\nM620 M\nG28",
        "machine_end_gcode": "; Bambu end sequence (sample placeholder)\nM400",
    })


def elegoo_style_project():
    """A project in Elegoo Slicer's layout, targeting an Elegoo printer."""
    return _project_3mf("Deja Vu1 sample in Elegoo Slicer project layout", {
        "printer_model": "Elegoo Centauri Carbon",
        "printer_settings_id": "Elegoo Centauri Carbon 0.4 nozzle",
        "print_settings_id": "0.16mm Optimal @Elegoo CC 0.4 nozzle",
        "filament_settings_id": ["Elegoo PETG @CC"],
        "inherits_group": ["0.16mm Optimal @Elegoo CC 0.4 nozzle", "Elegoo PETG @CC",
                           "Elegoo Centauri Carbon 0.4 nozzle"],
        "different_settings_to_system": ["brim_width", "", ""],
        "filament_colour": ["#3B82F6"],
        "filament_type": ["PETG"],
        "layer_height": "0.16",
        "brim_width": "4",
        "nozzle_diameter": ["0.4"],
        "printable_area": ["0x0", "256x0", "256x256", "0x256"],
        "printable_height": "256",
        "machine_start_gcode": "; Elegoo start sequence (sample placeholder)\nG28",
    })


SAMPLES = {
    "calibration_cube_20mm.gcode": calibration_cube,
    "two_colour_coaster.gcode": two_colour_coaster,
    "unsafe_example_purge_past_bed.gcode": unsafe_example,
    "dock_bracket.stl": dock_bracket_stl,
    "sample_bambu_studio_layout.3mf": bambu_style_project,
    "sample_elegoo_slicer_layout.3mf": elegoo_style_project,
}


def build(name):
    data = SAMPLES[name]()
    return data.encode("utf-8") if isinstance(data, str) else data
